 version: "3.7"
 services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm start"
    ports:
      -  '3000:3000'
    working_dir: /app
    volumes: 
      - ./app:/app
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: 
       MYSQL_DB: fincoura
  mysql:
    image: mysql:5.7
    volumes: 
      -  mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: fincoura
      MYSQL_USER: ROOT
      MYSQL_ALLOW_EMPTY_PASSWORD: ROOT
    ports:
        - "9806:3306"

  fincoura-server:
    container_name: fincoura-server
    build: ./server
    image: php:8.1-apache
    volumes: 
      - ./server:/var/www/html/
      - ./server/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
    depends_on:
      - mysql
    networks:
      - default
   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8060:80'
    restart: always
    environment:
        PMA_HOST: mysql
    depends_on:
        - mysql
    

 volumes:
    mysql-data:
